name: "Bug Report"
description: "Report a bug or issue with the application."
labels: ["bug"]
title: "[bug] "
body:
  - type: markdown
    attributes:
      value: "Describe the bug or issue in detail to help us reproduce it."
  - type: input
    id: version
    attributes:
      label: "Version"
      description: "The version of the application where the bug was found."
      placeholder: "e.g., v1.0.0"
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "The environment where the bug occurred."
      placeholder: "e.g., FireFox 142, Chrome 140 or Safari 18"
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: "Description"
      description: "Describe the bug or issue in detail."
      placeholder: "A clear and concise description of the bug."
      render: markdown
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the behavior."
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll down to...
        4. See error
      render: markdown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Paste any relevant logs or add screenshots."
      placeholder: "Error messages, stack traces, or screenshots."
